with CTE as (
    SELECT
    TO_TIMESTAMP(STARTED_AT)  AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT) ) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT) ) AS HOUR_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT) ) AS DAYNAME,

    CASE 
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT) ) IN ('Sat','Sun') 
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
    END AS DAY_TYPE,
    CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2) 
    then 'winter'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN'
    END AS STATION_OF_YEAR
        from {{ source('demo', 'BIKE') }}
    where STARTED_AT != 'STARTED_AT'
)

select 
*
from CTE