with CTE as (
    SELECT
    TO_TIMESTAMP(STARTED_AT)  AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT) ) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT) ) AS HOUR_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT) ) AS DAYNAME,

    CASE 
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT) ) IN ('Sat','Sun') 
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
    END AS DAY_TYPE,
  
  {{ get_season('STARTED_AT') }} as SEASON_OF_YEAR

        from {{ source('demo', 'BIKE') }}
    where STARTED_AT != 'STARTED_AT'
)

select 
*
from CTE